import { describe, expect, it } from "vitest";
import {
  emitContracts,
  type LocaleFile,
  type Namespace,
} from "../core/emit/contracts";

const locales3 = ["en-US", "zh-CN", "zh-HK"] as const;

describe("emitContracts", () => {
  it("返回文件头注释", () => {
    const out = emitContracts([], [], []);
    expect(out).toContain("/**");
    expect(out).toContain("AUTO-GENERATED by i18next-kit — DO NOT EDIT.");
    expect(out).toContain("*/");
  });

  it("返回每个 namespace 的 type import", () => {
    const namespaces: Namespace[] = [
      { name: "common", typeName: "CommonMessage" },
      { name: "user-management", typeName: "UserManagementMessage" },
      { name: "file", typeName: "FileMessage" },
    ];
    const result = emitContracts(namespaces, [], ["en-US"]);

    expect(result).toContain(
      `import type { CommonMessage } from './base/common';`
    );
    expect(result).toContain(
      `import type { UserManagementMessage } from './base/user-management';`
    );
    expect(result).toContain(`import type { FileMessage } from './base/file';`);
  });

  it("为每个 (locale, namespace) 生成 value import，并包含 LocaleContract 与 satisfies", () => {
    const namespaces: Namespace[] = [
      { name: "common", typeName: "CommonMessage" },
      { name: "user-management", typeName: "UserManagementMessage" },
      { name: "file", typeName: "FileMessage" },
    ];
    const localeFiles: LocaleFile[] = [
      { locale: "en-US", namespace: "common" },
      { locale: "zh-CN", namespace: "common" },
      { locale: "zh-HK", namespace: "common" },
    ];
    const result = emitContracts(namespaces, localeFiles, [...locales3]);

    expect(result).toContain(`import enUSCommon from './en-US/common';`);
    expect(result).toContain(`import zhCNCommon from './zh-CN/common';`);
    expect(result).toContain(`import zhHKCommon from './zh-HK/common';`);
    expect(result).toContain(
      `import type { CommonMessage } from './base/common';`
    );
    expect(result).toContain(
      `import type { UserManagementMessage } from './base/user-management';`
    );
    expect(result).toContain(`import type { FileMessage } from './base/file';`);
    expect(result).toContain("type LocaleContract = {");
    expect(result).toContain("  common: CommonMessage;");
    expect(result).toContain("export const contracts = {");
    expect(result).toContain(
      `satisfies Record<'en-US' | 'zh-CN' | 'zh-HK', LocaleContract>`
    );
  });

  it("完整矩阵时包含 quoted namespace 与 Record 断言（对齐 phase-1）", () => {
    const out = emitContracts(
      [
        { name: "common", typeName: "CommonMessage" },
        { name: "user-management", typeName: "UserManagementMessage" },
        {
          name: "file",
          typeName: "FileMessage",
        },
      ],
      [
        { locale: "en-US", namespace: "common" },
        { locale: "en-US", namespace: "user-management" },
        { locale: "en-US", namespace: "file" },
        { locale: "zh-CN", namespace: "common" },
        { locale: "zh-CN", namespace: "user-management" },
        { locale: "zh-CN", namespace: "file" },
        {
          locale: "zh-HK",
          namespace: "common",
        },
        {
          locale: "zh-HK",
          namespace: "user-management",
        },
        {
          locale: "zh-HK",
          namespace: "file",
        },
      ],
      ["en-US", "zh-CN", "zh-HK"]
    );

    expect(out).toContain(`import enUSCommon from './en-US/common';`);
    expect(out).toContain(`import enUSFile from './en-US/file';`);
    expect(out).toContain(
      `import zhCNUserManagement from './zh-CN/user-management';`
    );
    expect(out).toContain(`import zhHKFile from './zh-HK/file';`);
    expect(out).toContain(
      `satisfies Record<'en-US' | 'zh-CN' | 'zh-HK', LocaleContract>`
    );
    expect(out).toContain("'user-management': UserManagementMessage");
    expect(out).toContain(`type LocaleContract = {
  common: CommonMessage;
  file: FileMessage;
  'user-management': UserManagementMessage;
};`);
  });
});
