import { describe, expect, it } from "vitest";
import { emitDts } from "../core/emit/dts";

describe("emitDts", () => {
  it("返回 dts 文件内容", () => {
    const out = emitDts();
    expect(out).toContain("/**");
    expect(out).toContain("AUTO-GENERATED by i18next-kit — DO NOT EDIT.");
    expect(out).toContain("import 'i18next';");
    expect(out).toContain(
      "import type { defaultNS, resourceNamespaces } from './generated-resources';"
    );
    expect(out).toContain("declare module 'i18next' {");
    expect(out).toContain("interface CustomTypeOptions {");
    expect(out).toContain("defaultNS: typeof defaultNS;");
    expect(out).toContain("resources: typeof resourceNamespaces;");
    expect(out).toContain("}");
    expect(out).toContain("export {};");
  });
});
