import { describe, expect, it } from "vitest";
import {
  createAlternation,
  createGlobPattern,
  createInitialResources,
  emitRuntime,
} from "../core/emit/runtime";

describe("emitRuntime", () => {
  it("输入 ['en-US', 'zh-CN'] 返回 './{en-US,zh-CN}/*.ts'", () => {
    const out = createGlobPattern(["en-US", "zh-CN"]);
    expect(out).toBe("./{en-US,zh-CN}/*.ts");
  });

  it("输入 ['en-US', 'zh-CN'] 返回 'en-US|zh-CN'", () => {
    const out = createAlternation(["en-US", "zh-CN"]);
    expect(out).toBe("en-US|zh-CN");
  });

  it("输入 ['en-US', 'zh-CN'] 返回 'en-US': {}, 'zh-CN': {}'", () => {
    const out = createInitialResources(["en-US", "zh-CN"]);
    expect(out).toBe("'en-US': {}, 'zh-CN': {}");
  });

  it("输入 ['en-US', 'zh-CN'] 返回 产物", () => {
    const out = emitRuntime(["en-US", "zh-CN"]);
    expect(out).toContain(`/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */
import i18n, {
  type InitOptions,
  type Resource,
  type ResourceKey,
} from 'i18next';
import { initReactI18next } from 'react-i18next';
import { defaultNS, resourceNamespaces } from './generated-resources';
import './contracts';

const modules: Record<string, unknown> = import.meta.glob(
    './{en-US,zh-CN}/*.ts',
    { eager: true },
  );
const resources: Resource = { 'en-US': {}, 'zh-CN': {} };
for (const p in modules) {
const match = p.match(/^\\.\\/(en-US|zh-CN)\\/(.+)\\.ts$/);
  if (!match) continue;
  const [, locale, ns] = match;
  const mod = modules[p] as { default: ResourceKey };
  (resources[locale] as Record<string, ResourceKey>)[ns] = mod.default;
}

export function initI18n(
  options?: Omit<InitOptions, 'resources' | 'defaultNS' | 'ns'>,
) {
  return i18n.use(initReactI18next).init({
    resources,
    defaultNS,
    ns: Object.keys(resourceNamespaces),
    fallbackLng: 'en-US',
    interpolation: { escapeValue: false },
    ...options,
  });
}
`);
  });
});
