import { describe, expect, it } from "vitest";
import { emitResources } from "../core/emit/resources";

describe("emitResources", () => {
  it("一个 namespace 正确结构", () => {
    const out = emitResources([
      {
        name: "common",
        typeName: "CommonMessage",
      },
      {
        name: "user-management",
        typeName: "UserManagementMessage",
      },
    ]);

    // 首次运行 vitest -u 会自动填入 snapshot，review 时肉眼确认即可
    expect(out).toMatchInlineSnapshot(`
      "/**
       * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
       */
      import type { CommonMessage } from "./base/common";
      import type { UserManagementMessage } from "./base/user-management";


      export const defaultNS = 'common' as const;

      export const resourceNamespaces = {
           common: {} as CommonMessage,
       'user-management': {} as UserManagementMessage,
        } as const;
        
      export type I18nNamespace = keyof typeof resourceNamespaces;
        "
    `);
  });

  it("kebab-case 的 key 会加引号", () => {
    const out = emitResources([
      {
        name: "common",
        typeName: "CommonMessage",
      },
      {
        name: "user-management",
        typeName: "UserManagementMessage",
      },
    ]);

    expect(out).toContain(`'user-management': {} as UserManagementMessage,`);
    expect(out).toContain("common: {} as CommonMessage,");
  });

  it("defaultNS 取字母序第一", () => {
    const out = emitResources([
      {
        name: "aule",
        typeName: "ZuleMessage",
      },
      {
        name: "alpha",
        typeName: "AlphaMessage",
      },
    ]);
    expect(out).toContain("export const defaultNS = 'alpha' as const;");
  });

  it("产物包含 AUTO-GENERATED 头", () => {
    const out = emitResources([
      {
        name: "x",
        typeName: "XMessage",
      },
    ]);

    expect(out).toContain(
      "/**\n * AUTO-GENERATED by i18next-kit — DO NOT EDIT.\n */"
    );
  });
});
