import { describe, expect, it } from "vitest";
import { emitResoureces } from "../core/emit/resources";

describe("emitResoureces", () => {
  it("一个 namespace 正确结构", () => {
    const out = emitResoureces([
      {
        name: "common",
        typeName: "CommonMessage",
      },
      {
        name: "user-management",
        typeName: "UserManagementMessage",
      },
    ]);

    // 首次运行 vitest 会自动填入 snapshot，review 时肉眼确认即可
    expect(out).toMatchInlineSnapshot(`
      "/**
       * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
       */
      import type CommonMessage from "../base/common"
      import type UserManagementMessage from "../base/user-management"


      export const defaultNS = common as const;

      export const resourceNamespaces = {
           common: {} as CommonMessage
       'user-management': {} as UserManagementMessage
        } as const;
        
      export type I18nNamespace = keyof typeof resourceNamespaces;
        "
    `);
  });
});
