/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */

import type { CommonMessage } from "./base/common";
import type { FileMessage } from "./base/file";
import type { UserManagementMessage } from "./base/user-management";

import enUSCommon from "./en-US/common";
import enUSFile from "./en-US/file";
import enUSUserManagement from "./en-US/user-management";
import zhCNCommon from "./zh-CN/common";
import zhCNFile from "./zh-CN/file";
import zhCNUserManagement from "./zh-CN/user-management";
import zhHKCommon from "./zh-HK/common";
import zhHKFile from "./zh-HK/file";
import zhHKUserManagement from "./zh-HK/user-management";

type LocaleContract = {
  common: CommonMessage;
  file: FileMessage;
  "user-management": UserManagementMessage;
};

export const contracts = {
  "en-US": {
    common: enUSCommon,
    file: enUSFile,
    "user-management": enUSUserManagement,
  },
  "zh-CN": {
    common: zhCNCommon,
    file: zhCNFile,
    "user-management": zhCNUserManagement,
  },
  "zh-HK": {
    common: zhHKCommon,
    file: zhHKFile,
    "user-management": zhHKUserManagement,
  },
} satisfies Record<"en-US" | "zh-CN" | "zh-HK", LocaleContract>;
