/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */
import i18n, {
  type InitOptions,
  type Resource,
  type ResourceKey,
} from "i18next";
import { initReactI18next } from "react-i18next";
import { defaultNS, resourceNamespaces } from "./generated-resources";
import "./contracts";

const modules: Record<string, unknown> = import.meta.glob(
  "./{en-US,zh-CN,zh-HK}/*.ts",
  { eager: true }
);
const resources: Resource = { "en-US": {}, "zh-CN": {}, "zh-HK": {} };
for (const p in modules) {
  if (Object.hasOwn(modules, p)) {
    const match = p.match(/^\.\/(en-US|zh-CN|zh-HK)\/(.+)\.ts$/);
    if (!match) {
      continue;
    }
    const [, locale, ns] = match;
    const mod = modules[p] as { default: ResourceKey };
    (resources[locale] as Record<string, ResourceKey>)[ns] = mod.default;
  }
}

export function initI18n(
  options?: Omit<InitOptions, "resources" | "defaultNS" | "ns">
) {
  return i18n.use(initReactI18next).init({
    resources,
    defaultNS,
    ns: Object.keys(resourceNamespaces),
    fallbackLng: "en-US",
    interpolation: { escapeValue: false },
    ...options,
  });
}
