/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */
import "i18next";
import type { defaultNS, resourceNamespaces } from "./generated-resources";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: typeof resourceNamespaces;
  }
}
