/**
 * Metadata for a namespace contract discovered in the base contracts folder.
 */
export type Namespace = { name: string; typeName: string };

/**
 * A locale-specific namespace file discovered in the i18n directory.
 */
export type LocaleFile = { locale: string; namespace: string };

/**
 * Create the generated locale contracts source code.
 *
 * @param namespaces - Namespace metadata discovered from base contract files.
 * @param localeFiles - Locale and namespace pairs discovered from locale folders.
 * @param locales - Locale order used in imports, object keys, and the `Record` type.
 * @returns TypeScript source code for the generated contracts module.
 * @example
 * ```ts
 * emitContracts([{ name: "common", typeName: "CommonMessage" }, { name: "user-management", typeName: "UserManagementMessage" }], [{ locale: "en-US", namespace: "common" }, { locale: "zh-CN", namespace: "common" }], ["en-US", "zh-CN"]) => "import type { CommonMessage } from './base/common'; import type { UserManagementMessage } from './base/user-management'; import enUSCommon from './en-US/common'; import zhCNCommon from './zh-CN/common'; type LocaleContract = { common: CommonMessage; user-management: UserManagementMessage }; export const contracts = { 'en-US': { common: enUSCommon }, 'zh-CN': { common: zhCNCommon } } satisfies Record<'en-US' | 'zh-CN', LocaleContract>;
 * ```
 */
export function emitContracts(
  namespaces: Namespace[],
  localeFiles: LocaleFile[],
  locales: string[]
): string {
  const HEADER = `/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */`;

  const sortedNs = [...namespaces].sort((a, b) => a.name.localeCompare(b.name));
  const typeImports = sortedNs
    .map((ns) => `import type { ${ns.typeName} } from './base/${ns.name}';`)
    .join("\n");

  const fileSet = new Set(
    localeFiles.map((f) => fileKey(f.locale, f.namespace))
  );

  // Include a namespace only when every locale has a matching source file.
  const complete = sortedNs.filter((ns) =>
    locales.every((loc) => fileSet.has(fileKey(loc, ns.name)))
  );

  const valueImports = createValueImports(locales, complete);

  const localeContract = `type LocaleContract = {\n${complete
    .map((ns) => `  ${formatKey(ns.name)}: ${ns.typeName};`)
    .join("\n")}\n};`;

  const localeUnion =
    locales.length > 0 ? locales.map((l) => `'${l}'`).join(" | ") : "never";

  const contractsBody = createContractsObject(locales, complete);

  //   console.log("contractsBody =>", contractsBody);

  const contractsExport =
    locales.length === 0
      ? `export const contracts = {} satisfies Record<${localeUnion}, LocaleContract>;`
      : `export const contracts = {\n${contractsBody}\n} satisfies Record<${localeUnion}, LocaleContract>;`;

  const parts = [HEADER];
  if (typeImports) {
    parts.push(typeImports);
  }
  if (valueImports) {
    parts.push(valueImports);
  }
  parts.push(localeContract, contractsExport);
  const result = parts.join("\n\n");
  return result;
}

/**
 * Create default imports for each complete locale and namespace pair.
 *
 * @param locales - Locales to generate imports for.
 * @param complete - Namespaces that are present for every locale.
 * @returns Default import statements for locale namespace modules.
 * @example
 * ```ts
 * createValueImports(["en-US", "zh-CN", "zh-HK"], [{ name: "common", typeName: "CommonMessage" }, { name: "user-management", typeName: "UserManagementMessage" }]) => "import enUSCommon from './en-US/common'; import zhCNCommon from './zh-CN/common'; import zhHKCommon from './zh-HK/common';"
 * ```
 */
function createValueImports(locales: string[], complete: Namespace[]): string {
  const result = locales
    .flatMap((locale) =>
      complete.map(
        (ns) =>
          `import ${valueBinding(locale, ns.name)} from './${locale}/${ns.name}';`
      )
    )
    .join("\n");
  return result;
}

/**
 * Create the object literal body for the generated contracts export.
 *
 * @param locales - Locales to include as top-level keys.
 * @param complete - Namespaces to include for each locale.
 * @returns Object literal entries for the generated contracts export.
 * @example
 * ```ts
 * createContractsObject(["en-US", "zh-CN", "zh-HK"], [{ name: "common", typeName: "CommonMessage" }, { name: "user-management", typeName: "UserManagementMessage" }]) => "  'en-US': { common: enUSCommon, user-management: enUSUserManagement },  'zh-CN': { common: zhCNCommon, user-management: zhCNUserManagement },  'zh-HK': { common: zhHKCommon, user-management: zhHKUserManagement }"
 * ```
 */
function createContractsObject(
  locales: string[],
  complete: Namespace[]
): string {
  if (locales.length === 0) {
    return "";
  }
  const result = locales
    .map((locale) => {
      const inner = complete
        .map(
          (ns) => `    ${formatKey(ns.name)}: ${valueBinding(locale, ns.name)},`
        )
        .join("\n");
      return `  '${locale}': {\n${inner}\n  }`;
    })
    .join(",\n");

  return result;
}

/**
 * Create a stable lookup key from a locale and namespace.
 *
 * @param locale - Locale name.
 * @param namespace - Namespace name.
 * @returns A lookup key that cannot collide with normal namespace text.
 * @example
 * ```ts
 * fileKey("en-US", "common") => "en-US\0common"
 * fileKey("zh-CN", "user-management") => "zh-CN\0user-management"
 * ```
 */
function fileKey(locale: string, namespace: string): string {
  return `${locale}\0${namespace}`;
}

/**
 * Create a valid JavaScript binding name from a locale and namespace.
 *
 * @param locale - Locale name.
 * @param namespaceName - Namespace name.
 * @returns A camel-cased binding name.
 * @example
 * ```ts
 * valueBinding("en-US", "common") => "enUSCommon"
 * valueBinding("zh-CN", "user-management") => "zhCNUserManagement"
 * ```
 */
function valueBinding(locale: string, namespaceName: string): string {
  return `${toCamelLocale(locale)}${toPascal(namespaceName)}`;
}

/**
 * Format an object key as either an identifier or a quoted property name.
 *
 * @param name - Key to format.
 * @returns A valid object key fragment.
 * @example
 * ```ts
 * formatKey("common") => "common"
 * formatKey("user-management") => "'user-management'"
 * ```
 */
function formatKey(name: string): string {
  return /^[a-zA-Z_$][\w$]*$/.test(name) ? name : `'${name}'`;
}

/**
 * Convert a locale name to camel case.
 *
 * @param locale - Locale name to convert.
 * @returns Camel-cased locale text.
 * @example
 * ```ts
 * toCamelLocale("en-US") => "enUS"
 * toCamelLocale("zh-CN") => "zhCN"
 * ```
 */
function toCamelLocale(locale: string) {
  const parts = locale.split("-");
  return parts
    .map((part, index) =>
      index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join("");
}

/**
 * Convert a namespace name to PascalCase.
 *
 * @param name - Namespace name to convert.
 * @returns Pascal-cased namespace text.
 * @example
 * ```ts
 * toPascal("common") => "Common"
 * toPascal("user-management") => "UserManagement"
 * ```
 */
function toPascal(name: string) {
  return name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}
