/**
 * Create the i18next module augmentation source code.
 *
 * @returns TypeScript declaration source for i18next custom type options.
 */
export function emitDts() {
  return `/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */
import 'i18next';
import type { defaultNS, resourceNamespaces } from './generated-resources';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: typeof resourceNamespaces;
  }
}
`;
}
