/**
 * @description 该函数会返回一段合法的 TypeScript 代码，表示 dts 文件内容
 * @returns - 返回一个字符串，表示 dts 文件内容
 */
export function emitDts() {
  return `/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */
import 'i18next';
import type { defaultNS, resourceNamespaces } from './generated-resources';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: typeof resourceNamespaces;
  }
}

export {};
`;
}
