interface Namespace {
  name: string;
  typeName: string;
}

/**
 * Create the generated resource namespace metadata source code.
 *
 * @param namespaces - Namespace metadata used to generate imports and keys.
 * @example
 * ```ts
 * const namespaces = [
 *   { name: 'common', typeName: 'CommonMessage' },
 *   { name: 'user-management', typeName: 'UserManagementMessage' },
 * ];
 * emitResources(namespaces);
 * ```
 * @returns TypeScript source code for the generated resources module.
 */
export function emitResources(namespaces: Namespace[]) {
  const entries = namespaces
    .map((ns) => ` ${formatKey(ns.name)}: {} as ${ns.typeName},`)
    .join("\n");

  const HEADER = `/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */`;

  const sorted = [...namespaces].sort((a, b) => a.name.localeCompare(b.name));
  const defaultNSName = sorted[0]?.name ?? "common";

  const body = `export const resourceNamespaces = {
    ${entries}
  } as const;`;

  const imports = namespaces
    .map((ns) => `import type { ${ns.typeName} } from "./base/${ns.name}";`)
    .join("\n");
  return `${HEADER}\n${imports}\n\n
export const defaultNS = '${defaultNSName}' as const;

${body}
  
export type I18nNamespace = keyof typeof resourceNamespaces;
  `;
}

/**
 * Format a resource namespace key as an identifier or quoted property name.
 *
 * @param name - Namespace key to format.
 * @example
 * ```ts
 * formatKey("user-management"); // "user-management"
 * formatKey("user management"); // "'user management'"
 * ```
 * @returns A valid object key fragment.
 */
function formatKey(name: string) {
  const REGEX = /^[a-zA-Z_$][\w$]*$/;
  return REGEX.test(name) ? name : `'${name}'`;
}
