export function emitRuntime(locales: string[]) {
  const globPattern = createGlobPattern(locales);
  const initialResources = createInitialResources(locales);
  const alternation = createAlternation(locales);

  const HEADER = `/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */`;

  const modules = `const modules: Record<string, unknown> = import.meta.glob(
    '${globPattern}',
    { eager: true },
  );`;

  const resources = `const resources: Resource = { ${initialResources} };`;

  return `${HEADER}
import i18n, {
  type InitOptions,
  type Resource,
  type ResourceKey,
} from 'i18next';
import { initReactI18next } from 'react-i18next';
import { defaultNS, resourceNamespaces } from './generated-resources';
import './contracts';

${modules}
${resources}
for (const p in modules) {
const match = p.match(/^\\.\\/(${alternation})\\/(.+)\\.ts$/);
  if (!match) continue;
  const [, locale, ns] = match;
  const mod = modules[p] as { default: ResourceKey };
  (resources[locale] as Record<string, ResourceKey>)[ns] = mod.default;
}

export function initI18n(
  options?: Omit<InitOptions, 'resources' | 'defaultNS' | 'ns'>,
) {
  return i18n.use(initReactI18next).init({
    resources,
    defaultNS,
    ns: Object.keys(resourceNamespaces),
    fallbackLng: 'en-US',
    interpolation: { escapeValue: false },
    ...options,
  });
}
`;
}

/**
 * @description 创建 glob 模式
 * @param locales - 语言列表
 * @returns - 返回一个字符串，表示 glob 模式
 * @example
 * ```ts
 * createGlobPattern(["en-US", "zh-CN"]) => "./{en-US,zh-CN}/*.ts"
 * ```
 */
export function createGlobPattern(locales: string[]) {
  return `./{${locales.join(",")}}/*.ts`;
}

/**
 * @description 创建 alternation
 * @param locales - 语言列表
 * @returns - 返回一个字符串，表示 alternation
 * @example
 * ```ts
 * createAlternation(["en-US", "zh-CN"]) => "en-US|zh-CN"
 * ```
 */
export function createAlternation(locales: string[]) {
  return locales.join("|");
}

/**
 * @description 创建 initialResources: 'en-US': {}, 'zh-CN': {}
 * @param locales - 语言列表
 * @returns - 返回一个字符串，表示 initialResources
 * @example
 * ```ts
 * createInitialResources(["en-US", "zh-CN"]) => "'en-US': {}, 'zh-CN': {}"
 * ```
 */
export function createInitialResources(locales: string[]) {
  return locales.map((locale) => `'${locale}': {}`).join(", ");
}
