/**
 * Create the generated runtime module source code.
 *
 * The generated module eagerly imports locale namespace files with
 * `import.meta.glob`, builds the i18next resources object, and exports
 * `initI18n()` for React applications.
 *
 * @param locales - Locales to include in the runtime glob pattern.
 * @returns TypeScript source code for the generated runtime module.
 */
export function emitRuntime(locales: string[]) {
  const globPattern = createGlobPattern(locales);
  const initialResources = createInitialResources(locales);
  const alternation = createAlternation(locales);

  const HEADER = `/**
 * AUTO-GENERATED by i18next-kit — DO NOT EDIT.
 */`;

  const modules = `const modules: Record<string, unknown> = import.meta.glob(
    '${globPattern}',
    { eager: true },
  );`;

  const resources = `const resources: Resource = { ${initialResources} };`;

  return `${HEADER}
import i18n, {
  type InitOptions,
  type Resource,
  type ResourceKey,
} from 'i18next';
import { initReactI18next } from 'react-i18next';
import { defaultNS, resourceNamespaces } from './generated-resources';
import './contracts';

${modules}
${resources}
for (const p in modules) {
  if (Object.hasOwn(modules, p)) {
    const match = p.match(/^\\.\\/(${alternation})\\/(.+)\\.ts$/);
    if (!match) {
      continue;
    }
    const [, locale, ns] = match;
    const mod = modules[p] as { default: ResourceKey };
    (resources[locale] as Record<string, ResourceKey>)[ns] = mod.default;
  }
}

export function initI18n(
  options?: Omit<InitOptions, 'resources' | 'defaultNS' | 'ns'>,
) {
  return i18n.use(initReactI18next).init({
    resources,
    defaultNS,
    ns: Object.keys(resourceNamespaces),
    fallbackLng: 'en-US',
    interpolation: { escapeValue: false },
    ...options,
  });
}
`;
}

/**
 * Create the `import.meta.glob` pattern for locale namespace modules.
 *
 * @param locales - Locales to include in the glob pattern.
 * @returns A glob pattern for generated runtime imports.
 * @example
 * ```ts
 * createGlobPattern(["en-US", "zh-CN"]) => "./{en-US,zh-CN}/*.ts"
 * ```
 */
export function createGlobPattern(locales: string[]) {
  return `./{${locales.join(",")}}/*.ts`;
}

/**
 * Create a regular expression alternation for locale names.
 *
 * @param locales - Locales to include in the alternation.
 * @returns A `|`-separated regular expression fragment.
 * @example
 * ```ts
 * createAlternation(["en-US", "zh-CN"]) => "en-US|zh-CN"
 * ```
 */
export function createAlternation(locales: string[]) {
  return locales.join("|");
}

/**
 * Create the initial i18next resources object entries.
 *
 * @param locales - Locales to initialize.
 * @returns Object literal entries for the generated resources object.
 * @example
 * ```ts
 * createInitialResources(["en-US", "zh-CN"]) => "'en-US': {}, 'zh-CN': {}"
 * ```
 */
export function createInitialResources(locales: string[]) {
  return locales.map((locale) => `'${locale}': {}`).join(", ");
}
